packages:
  - .
patchedDependencies:
  expo-task-manager@55.0.9: patches/expo-task-manager@55.0.9.patch
  '@kingstinct/react-native-healthkit@13.3.0': patches/@kingstinct__react-native-healthkit@13.3.0.patch
